/**
 * init-project.mjs — Create the project folder structure for /proposal.
 * Usage: node skills/proposal/scripts/init-project.mjs <student-slug>
 */
import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { PROJECT_ROOT, assertSlug, updateRunManifest } from './project-utils.mjs';

const SCRIPT_DIR = dirname(fileURLToPath(import.meta.url));
const scriptPath = (name) => JSON.stringify(join(SCRIPT_DIR, name));

const slug = process.argv[2];
try {
  assertSlug(slug);
} catch (error) {
  console.error(`Invalid slug: ${error.message}`);
  process.exit(1);
}

const projectDir = join(PROJECT_ROOT, 'projects', slug);
const manifestPath = join(projectDir, 'run-manifest.json');
if (existsSync(manifestPath)) {
  let manifest;
  try {
    manifest = JSON.parse(readFileSync(manifestPath, 'utf-8'));
  } catch {
    console.error(`BLOCKED: invalid existing run manifest: ${manifestPath}`);
    process.exit(1);
  }
  const hasDownstream = ['binder.md', 'proposal-final.md', 'proposal-draft.md'].some((name) => existsSync(join(projectDir, name)));
  if (manifest.status !== 'awaiting-intake' || hasDownstream) {
    console.error(`BLOCKED: project already has an active or completed run: ${projectDir}`);
    process.exit(1);
  }
}
const dirs = [
  projectDir,
  join(projectDir, 'gap-analysis'),
  join(projectDir, 'evidence-ranking'),
  join(projectDir, 'verifier'),
];

for (const dir of dirs) {
  if (!existsSync(dir)) {
    mkdirSync(dir, { recursive: true });
    console.log(`Created: ${dir}`);
  } else {
    console.log(`Exists:  ${dir}`);
  }
}

const voicePath = join(projectDir, 'voice-sample.txt');
if (!existsSync(voicePath)) {
  writeFileSync(voicePath, '# Voice Sample\n\nStatus: DEFAULT_NEUTRAL\nNo student sample supplied; humanizer must use the neutral baseline.\n', 'utf-8');
  console.log(`Created: ${voicePath}`);
}
updateRunManifest(projectDir, { status: 'awaiting-intake' });

const readmePath = join(projectDir, 'README.md');
if (!existsSync(readmePath)) {
  writeFileSync(readmePath, `# Project: ${slug}\n\nGenerated by /proposal skill.\n\n## Artifacts\n\n- profile.json — raw CV intake, then structured profile\n- posting.json — raw posting intake, then structured posting data\n- posting-raw.txt / cv-raw.txt — extracted source text\n- phase-0-provenance.md — input/extraction ledger\n- run-manifest.json — current intake generation/lineage\n- voice-sample.txt — supplied sample or explicit neutral baseline\n- professor-research.json — professor/lab research\n- gap-analysis/ — gap dossier and provenance\n- evidence-ranking/ — scored evidence table\n- verifier/ — verifier verdict\n- proposal-draft.md — pre-humanization draft\n- proposal-final.md — humanized proposal\n- binder.md — final binder\n- binder.provenance.md — audit trail\n`, 'utf-8');
  console.log(`Created: ${readmePath}`);
}

console.log(`\nProject initialized: ${projectDir}`);
console.log('Next steps:');
console.log(`  1. Parse posting: node ${scriptPath('parse-posting.mjs')} ${slug} <posting-path>`);
console.log(`  2. Parse CV: node ${scriptPath('parse-cv.mjs')} ${slug} <cv-path>`);
console.log(`  3. Register verified structured fields: node ${scriptPath('register-structured.mjs')} ${slug}`);
console.log(`  4. Set voice sample: node ${scriptPath('find-voice-sample.mjs')} ${slug} --statement <path> OR --sample <path>`);
console.log(`  5. Research professor: node ${scriptPath('research-professor.mjs')} ${slug}`);
