/**
 * init-project.mjs — Create project folder structure for /proposal skill.
 *
 * Usage:
 *   node skills/proposal/scripts/init-project.mjs <student-slug>
 *
 * Creates:
 *   projects/<student-slug>/
 *   ├── gap-analysis/
 *   ├── evidence-ranking/
 *   ├── verifier/
 *   └── (artifacts created by subagents)
 */

import { mkdirSync, existsSync, writeFileSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = join(__dirname, '..', '..', '..');

const slug = process.argv[2];

if (!slug) {
  console.error('Usage: node skills/proposal/scripts/init-project.mjs <student-slug>');
  console.error('  slug: lowercase, hyphenated identifier (e.g., "john-doe-gatech-2027")');
  process.exit(1);
}

// Validate slug
if (!/^[a-z0-9]+(-[a-z0-9]+)*$/.test(slug)) {
  console.error('Invalid slug. Use lowercase letters, numbers, and hyphens only.');
  process.exit(1);
}

const projectDir = join(REPO_ROOT, 'projects', slug);

const dirs = [
  projectDir,
  join(projectDir, 'gap-analysis'),
  join(projectDir, 'evidence-ranking'),
  join(projectDir, 'verifier'),
];

for (const dir of dirs) {
  if (!existsSync(dir)) {
    mkdirSync(dir, { recursive: true });
    console.log(`Created: ${dir}`);
  } else {
    console.log(`Exists:  ${dir}`);
  }
  }

// Create README for the project
const readmePath = join(projectDir, 'README.md');
if (!existsSync(readmePath)) {
  const readme = `# Project: ${slug}

Generated by /proposal skill.

## Artifacts

- \`profile.json\` — Structured CV extraction
- \`voice-sample.txt\` — Writing sample for voice matching
- \`posting.json\` — Structured position posting data
- \`posting-raw.txt\` — Raw text from posting
- \`professor-research.json\` — Professor/lab web research
- \`professor-search-plan.txt\` — Search queries used
- \`gap-analysis/\` — Gap dossier (general + lab-specific) + provenance
- \`evidence-ranking/\` — Scored evidence table
- \`verifier/\` — Verifier verdict
- \`proposal-draft.md\` — Raw proposal (pre-humanization)
- \`proposal-final.md\` — Humanized proposal
- \`binder.md\` — Layered binder (final output)
- \`binder.provenance.md\` — Full audit trail
`;
  writeFileSync(readmePath, readme);
  console.log(`Created: ${readmePath}`);
}

console.log(`\nProject initialized: ${projectDir}`);
console.log('Next steps:');
console.log('  1. Parse posting: node skills/proposal/scripts/parse-posting.mjs ' + slug + ' <posting-path-or-url>');
console.log('  2. Parse CV: node skills/proposal/scripts/parse-cv.mjs ' + slug + ' <cv.pdf>');
console.log('  3. Set voice sample: node skills/proposal/scripts/find-voice-sample.mjs ' + slug + ' --statement <path> OR --sample <path>');
console.log('  4. Research professor: node skills/proposal/scripts/research-professor.mjs ' + slug);
