/**
 * render.mjs — render Vitruvius host adapters into a target project.
 *
 * Nothing rendered here is committed. The authoritative sources are
 * installer/contract.mjs (commands and install targets),
 * references/host-rules.md (the shared ruleset), and agents/*.md (role
 * contracts). This module renders the files those sources imply;
 * installer/install.mjs copies the hand-authored host files and calls this
 * renderer. Keeping derived output out of the repository is why the host
 * packages under installer/hosts/ hold only the few files a human writes.
 *
 * Usage (from installer/install.mjs or a test):
 *   import { renderAdapters } from "./render.mjs";
 *   renderAdapters({ targetRoot: "/tmp/target", hostIds: ["opencode"] });
 */

import { readFileSync, writeFileSync, mkdirSync, existsSync, readdirSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import { commands, categories, hosts } from "./contract.mjs";
import { parseFrontmatterObject } from "../scripts/yaml-frontmatter.mjs";

const REPO_ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const normalizeLineEndings = (value) => value.replace(/\r\n/g, "\n");

function parseToolsList(value) {
  const match = String(value ?? "").match(/^\[(.*)\]$/);
  return match ? match[1].split(",").map((entry) => entry.trim()).filter(Boolean) : [];
}

// Role adapters are generated from the canonical agents/*.md manifest so the
// OpenCode subagents cannot drift from their role contracts. A read-only role
// (declares neither Write nor Edit) gets the write/edit denials.
function agentAdapterContent(role, canonical) {
  const frontmatter = parseFrontmatterObject(canonical);
  const name = typeof frontmatter.name === "string" ? frontmatter.name : role;
  const purpose = typeof frontmatter.role === "string"
    ? frontmatter.role.charAt(0).toLowerCase() + frontmatter.role.slice(1)
    : role;
  const tools = parseToolsList(frontmatter.tools);
  const readOnly = !tools.includes("Write") && !tools.includes("Edit");
  return [
    "---",
    `description: Vitruvius ${name} role (${purpose}). Canonical definition: agents/${name}.md - Read it and follow it exactly.`,
    "mode: subagent",
    readOnly ? "tools:\n  write: false\n  edit: false" : "tools:",
    "---",
    "",
    `1. Read the file agents/${name}.md from the repo root and follow it exactly.`,
    `2. If that file is missing, refuse the task and report BLOCKED: role definition agents/${name}.md not found - do not improvise the role.`,
    "",
  ].join("\n");
}

function generateMarkdownCommand(cmd) {
  const frontmatter = `---
name: ${cmd.name}
description: ${cmd.description}
argument-hint: ${cmd.argumentHint}
---`;

  const body = `# ${cmd.name}

${cmd.description}

## Usage

\`\`\`
/${cmd.name} ${cmd.argumentHint}
\`\`\`

## Category

${categories[cmd.category]?.label || cmd.category}
`;

  return `${frontmatter}\n\n${body.trimEnd()}\n`;
}

function generateCommandCodeMod() {
  const commandList = commands
    .map((cmd) => `  {\n    name: "${cmd.name}",\n    description: "${cmd.description}",\n    argumentHint: "${cmd.argumentHint}",\n  },`)
    .join("\n\n");

  return `/**
 * Command Code mod — auto-generated by installer/install.mjs
 * Do not edit directly. Edit installer/contract.mjs and reinstall.
 */

export const commands = [
${commandList}
];
`;
}

function canonicalRoleFiles(repoRoot) {
  const agentsDir = join(repoRoot, "agents");
  if (!existsSync(agentsDir)) return [];
  // README.md is the tree's index, not a dispatchable role.
  return readdirSync(agentsDir).filter((file) => file.endsWith(".md") && file !== "README.md").sort();
}

/**
 * Render the generated adapter files for the requested hosts into `targetRoot`.
 * Returns the list of target-relative paths written.
 */
export function renderAdapters({ repoRoot = REPO_ROOT, targetRoot, hostIds } = {}) {
  if (!targetRoot) throw new Error("renderAdapters requires a targetRoot");
  const selected = hostIds ? hosts.filter((host) => hostIds.includes(host.id)) : hosts;
  const written = [];

  const emit = (relPath, content) => {
    const file = join(targetRoot, relPath);
    mkdirSync(dirname(file), { recursive: true });
    writeFileSync(file, normalizeLineEndings(content));
    written.push(relPath);
  };

  const roleFiles = canonicalRoleFiles(repoRoot);
  const ruleset = () =>
    normalizeLineEndings(readFileSync(join(repoRoot, "references", "host-rules.md"), "utf-8"));

  for (const host of selected) {
    if (host.commands) {
      for (const cmd of commands) {
        emit(join(host.commands.dir, `${cmd.name}.${host.commands.ext}`), generateMarkdownCommand(cmd));
      }
    }
    if (host.roles) {
      for (const file of roleFiles) {
        const canonical = readFileSync(join(repoRoot, "agents", file), "utf-8");
        emit(join(host.roles.dir, file), agentAdapterContent(file.replace(/\.md$/, ""), canonical));
      }
    }
    if (host.ruleset) emit(host.ruleset.file, ruleset());
    if (host.mod) emit(host.mod.file, generateCommandCodeMod());
  }

  return written;
}
